source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               intro/,\
               icons/,\
               i18n/,\
               help/,\
               fragment.e4xmi,\
               examples/,\
               build.properties,\
               about_files/,\
               about.html

