

all:
	./build/build  
        
clean:
	rm -rf doc
	rm -f de/toem/flux/*.ts
	rm -f de/toem/flux/examples/*.ts	
	rm -f jsweet/src/main/java/de/toem/flux/*.java
	rm -f jsweet/src/main/java/de/toem/flux/examples/*.java	
trace:
